### ISSUE TITLE
Labelling

### ISSUE THREAD

**Issue by stevenjh** [patros/docker-geoserver-azure-web-app#1]
I'm running this image and attempting to add labeling with no success, checking the pre-installed data/services/styles against `tiger_roads` and `poi`, they do no render their labels and log the below errors 

```
2019-09-19 05:43:15,009 ERROR [renderer.label] - Error adding label to the label cache
java.lang.NullPointerException
2019-09-19 05:43:15,016 INFO [geoserver.wms] - 
Request: getMap
	Angle = 0.0
	BaseUrl = http://woods-geoserver.azurewebsites.net:80/geoserver/
	Bbox = SRSEnvelope[-74.01502668857574 : -74.00814950466156, 40.706223249435425 : 40.714462995529175]
	BgColor = java.awt.Color[r=255,g=255,b=255]
	Buffer = 0
	CQLFilter = null
	Crs = GEOGCS["WGS 84", 
  DATUM["World Geodetic System 1984", 
    SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]], 
    AUTHORITY["EPSG","6326"]], 
  PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]], 
  UNIT["degree", 0.017453292519943295], 
  AXIS["Geodetic longitude", EAST], 
  AXIS["Geodetic latitude", NORTH], 
  AUTHORITY["EPSG","4326"]]
	Elevation = []
	Env = {}
	Exceptions = application/vnd.ogc.se_inimage
	FeatureId = null
	FeatureVersion = null
	Filter = null
	Filters = null
	Format = image/png
	FormatOptions = {}
	Get = true
	Height = 768
	Interpolations = []
	Layers = [org.geoserver.wms.MapLayerInfo@f1b59c92]
	MaxFeatures = null
	Palette = null
	RawKvp = {EXCEPTIONS=application/vnd.ogc.se_inimage, FORMAT=image/png, REQUEST=GetMap, SRS=EPSG:4326, BBOX=-74.01502668857574,40.706223249435425,-74.00814950466156,40.714462995529175, VERSION=1.1.1, STYLES=, WIDTH=641, SERVICE=WMS, HEIGHT=768, TRANSPARENT=true, LAYERS=tiger:poi}
	RemoteOwsType = null
	RemoteOwsURL = null
	Request = GetMap
	RequestCharset = UTF-8
	ScaleMethod = null
	Sld = null
	SldBody = null
	SldVersion = null
	SortBy = null
	SortByArrays = null
	SRS = EPSG:4326
	StartIndex = null
	StyleBody = null
	StyleFormat = sld
	Styles = [StyleImpl[ name=poi]]
	StyleUrl = null
	StyleVersion = null
	Tiled = false
	TilesOrigin = null
	Time = []
	Transparent = true
	ValidateSchema = false
	Version = 1.1.1
	ViewParams = null
	Width = 641
```

I'm wondering if it is related to this issue about no fonts?
https://gis.stackexchange.com/questions/238045/geoserver-doesnt-render-labels

Thanks!

**Comment by coderpatros** [comment]
@stevenjh I think you're right.

I've pushed up a change to the base container and triggered a new build.

It might take a little while but there should be a new image with the `latest` tag before too long.

Let me know how it goes.

**Comment by stevenjh** [comment]
Thanks for looking into this!
I see the update through against the [base](https://hub.docker.com/r/coderpatros/geoserver-base/tags) but nothing in the [azure build](https://hub.docker.com/r/coderpatros/geoserver-azure-web-app/tags).
Is there another build step that needs to be triggered?

**Comment by coderpatros** [comment]
I'm part way through changing how I put together this image. Turns out I broke my build @stevenjh. The one I've triggered now should work.

**Comment by coderpatros** [comment]
@stevenjh the new build is ready to go. Please let me know if it solves your issue or not.

**Comment by stevenjh** [comment]
Hi @patros, thanks for looking at this and can confirm, there are now labels! Thanks again!
